# Generated by Django 4.2.6 on 2023-10-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='img',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
