# Generated by Django 4.2.6 on 2023-10-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_author_home_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
