# Generated by Django 4.2.6 on 2023-10-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_home_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='decriptions',
            field=models.TextField(blank=True),
        ),
    ]
