# Generated by Django 4.2.6 on 2023-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='img',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
